---
# ----------------------------- Initial checks -------------------------------

- include_tasks: "install-virt-v2v.yml"


# ------------------- Transport Method Configuration -----------------------

- include_tasks: "install-transport-{{ v2v_transport_method }}.yml"

# ----------------------- Provider Configuration ----------------------------

- include_tasks: "install-provider-{{ v2v_host_type }}.yml"

- include_tasks: "install-provider-ssl-ca-chain.yml"


# ----------------------- Validate Installation -----------------------------

- include_tasks: "install-validate-{{ v2v_host_type }}.yml"
