---
- name: Install packages for OpenStack appliance
  yum:
    name:
      - python2-openstackclient
      - virtio-win
      - python-six
    state: "{{ v2v_yum_check }}"

- name: Create cron job for log cleanup
  copy:
    src: etc/cron.daily/virt-v2-logs
    dest: /etc/cron.daily/virt-v2-logs
    owner: root
    group: root
    mode: 0755
