---
# NOTE: We cannot arbitrarily remove keys from VDSM hosts. It is common to have
#       keys set up for other purposes and not just conversion host.
# - set_fact:
#     ssh_config_path: "/var/lib/vdsm/.ssh"
#     ssh_config_owner: "vdsm"
#   when:
#     - "v2v_host_type == 'rhevm'"

- name: Set facts ssh_config_path, ssh_config_owner
  set_fact:
    ssh_config_path: "/root/.ssh"
    ssh_config_owner: "root"
  when:
    - "v2v_host_type == 'openstack'"

- name: Delete SSH private key file for VMware host
  file:
    path: "{{ ssh_config_path }}/id_rsa"
    state: absent
  when:
    - "v2v_ssh_private_key is defined"
    - "ssh_config_path is defined"
